let BUSINESS_SETTINGS_DEFAULT = {}

BUSINESS_SETTINGS_DEFAULT.DATE_FORMAT_yyyyMMddHHmmss = "yyyy-MM-dd HH:mm:ss";
BUSINESS_SETTINGS_DEFAULT.DATE_FORMAT_QUERY_WHERE_CLAUSE_yyyyMMddHHmmss = "yyyy-MM-dd HH:mm:ss";
BUSINESS_SETTINGS_DEFAULT.CURRENCY_DOLLAR = "$"; CURRENCY_RS = "Rs";
BUSINESS_SETTINGS_DEFAULT.DEFAULT_DECIMAL = " #,##0.00";
BUSINESS_SETTINGS_DEFAULT.DEFAULT_SMS_SENDNING_MEDIA_ID = "1";
BUSINESS_SETTINGS_DEFAULT.DEFAULT_PYAMENT_COLLECTION_SMS_ID = "1";
BUSINESS_SETTINGS_DEFAULT.DEFAULT_SALE_RECEIPT_SMS_ID = "2";
BUSINESS_SETTINGS_DEFAULT.DEFAULT_REMINDER_MESSAGE_SMS_ID = "3";
BUSINESS_SETTINGS_DEFAULT.DEFAULT_PREVIOUS_DEBT_SMS_ID = "4";
BUSINESS_SETTINGS_DEFAULT.DEFAULT_SEND_REMINDER_EMAIL_DUE_DEBT_BEFORE_DAYS = "30";
BUSINESS_SETTINGS_DEFAULT.DEFAULT_SEND_SUMMARY_DAY_SALE_TIME = "22:00";
BUSINESS_SETTINGS_DEFAULT.AUTO_CALCULATE_BUY_PRICE_PERCENTAGE = "10.0";
BUSINESS_SETTINGS_DEFAULT.DEBT_TOTAL_INSTALLMENTS = "3";
BUSINESS_SETTINGS_DEFAULT.DEBT_INSTALLMENT_SCHEDULE_DAYS = "30";
BUSINESS_SETTINGS_DEFAULT.DEFAULT_CATEGORY_ID = "0";
BUSINESS_SETTINGS_DEFAULT.DEFAULT_IS_SHOW_CUSTOMER_ADJUSTMENT = "Y";
module.exports = BUSINESS_SETTINGS_DEFAULT;