let CONTACT_US_TYPE = {}

CONTACT_US_TYPE.CONTACT_US_TYPE = "INSTRUCTIONS_OPENED";
CONTACT_US_TYPE.BASICINFO_OPENED = "INSTRUCTIONS_OPENED";
CONTACT_US_TYPE.BASICINFO_SAVED_ERROR = "BASICINFO_SAVED_ERROR";
CONTACT_US_TYPE.BASICINFO_SAVED_SUCCESS = "BASICINFO_SAVED_SUCCESS";
CONTACT_US_TYPE.BASICINFO_SAVED_SUCCESS_COUNTRY = "BASICINFO_SAVED_SUCCESS_COUNTRY";
CONTACT_US_TYPE.APP_DOWNLOADED = "APP_DOWNLOADED";

CONTACT_US_TYPE.IMEI_FETCHED_SUCCESS = "IMEI_FETCHED_SUCCESS";
CONTACT_US_TYPE.IMEI_FETCHED_ERROR = "IMEI_FETCHED_ERROR";
CONTACT_US_TYPE.NEW_BUSINEESS_TOCREATE = "NEW_BUSINEESS_TOCREATE";
CONTACT_US_TYPE.BUSINESS_TYPE_WITHOUT_CATALOG = "BUSINESS_TYPE_WITHOUT_CATALOG";
CONTACT_US_TYPE.BUSINESS_TYPE_WITH_CATALOG = "BUSINESS_TYPE_WITH_CATALOG";
CONTACT_US_TYPE.EXISTING_BUSINESS_TO_RESTORE = "EXISTING_BUSINESS_TO_RESTORE";
CONTACT_US_TYPE.NEW_BUSINESS_SAVED_SUCCESS = "NEW_BUSINESS_SAVED_SUCCESS";
CONTACT_US_TYPE.NEW_BUSINESS_SAVE_ERROR = "NEW_BUSINESS_SAVE_ERROR";
CONTACT_US_TYPE.NEW_USER_SAVED_SUCCESS = "NEW_USER_SAVED_SUCCESS";

CONTACT_US_TYPE.NEW_USER_SAVE_ERROR = "NEW_USER_SAVE_ERROR";
CONTACT_US_TYPE.EXISTING_BUSINESS_RESTORE_ERROR = "EXISTING_BUSINESS_RESTORE_ERROR";
CONTACT_US_TYPE.EXISTING_BUSINESS_RESTORED_SUCCESS = "EXISTING_BUSINESS_RESTORED_SUCCESS";
CONTACT_US_TYPE.USER_LOGGED_IN_VIA_KEEPT_LOGGED_IN = "USER_LOGGED_IN_VIA_KEEPT_LOGGED_IN";
CONTACT_US_TYPE.USER_LOGGED_IN_SUCCESS = "USER_LOGGED_IN_SUCCESS";
CONTACT_US_TYPE.USER_LOGGED_IN_ERROR = "USER_LOGGED_IN_ERROR";
CONTACT_US_TYPE.CREATE_CATEGORY = "CREATE_CATEGORY";
CONTACT_US_TYPE.CREATE_PRODUCT = "CREATE_PRODUCT";
CONTACT_US_TYPE.SERVER_EXCEPTION = "SERVER_EXCEPTION";
module.exports = CONTACT_US_TYPE;